### ISSUE TITLE
please provide headless version (as a library)

### ISSUE THREAD

**Issue by ghost** [errozero/poly-synth#1]
Not sure this might be too much to ask, but I would use it in my js app if I had it in the form of a library (no UI at all).  I was looking for something like that for a long time. I can send standard MIDi note-on, note-off messages, that's all I need. Well, may be sustain pedal, too. But I need it to sound like electric piano instruments (e.g. similar to those found on Roland's E-Piano bank). Is it possible?

**Comment by errozero** [comment]
It can already be used without the UI, just use the synth.instrument.js file. The noteOn and noteOff functions receive a midi note number, the setControlValue function can be used to set any of the controls, just send a control id and a midi value. 

You might have to make a few minor modifications if you don't want to use the small app.js file.

The other things you have mentioned would have to be done by yourself.
